const fs = require('fs');

const lines = [
  'use client';,
  import React, { useEffect, useState, useRef } from 'react';,
  import Link from 'next/link';,
  import { ChevronLeft, Send, ShieldCheck, LockKeyhole } from 'lucide-react';,
  import { io } from 'socket.io-client';,
  import CryptoJS from 'crypto-js';,
  `,
  const SECRET_KEY = 'PL_OS_SECRET_SECURE_KEY_2026';,
  `,
  export default function ChatPage() {,
    const [socket, setSocket] = useState(null);,
    const [messages, setMessages] = useState([]);,
    const [input, setInput] = useState('');,
    const [userId, setUserId] = useState('');,
    const messagesEndRef = useRef(null);,
  `,
    useEffect(() => {,
      const newUserId = Math.random().toString(36).substring(2, 9);,
      setUserId(newUserId);,
      const newSocket = io(window.location.origin);,
      setSocket(newSocket);,
  `,
      newSocket.on('encrypted_message', (data) => {,
        try {,
          const bytes = CryptoJS.AES.decrypt(data.encryptedText, SECRET_KEY);,
          const decryptedMessage = bytes.toString(CryptoJS.enc.Utf8);,
          if(decryptedMessage) {,
            setMessages((prev) => [...prev, { ...data, decryptedText: decryptedMessage }]);,
          },
        } catch (err) {},
      });,
      return () => newSocket.disconnect();,
    }, []);,
  `,
    useEffect(() => {,
      messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });,
    }, [messages]);,
  `,
    const sendMessage = (e) => {,
      e.preventDefault();,
      if (!input.trim() || !socket) return;,
      const encryptedString = CryptoJS.AES.encrypt(input, SECRET_KEY).toString();,
      const msgPayload = {,
        id: Math.random().toString(36).substring(2, 9),,
        sender: userId,,
        encryptedText: encryptedString,,
        time: new Date().toLocaleTimeString('pl-PL', { hour: '2-digit', minute: '2-digit' }),
      };,
      setMessages((prev) => [...prev, { ...msgPayload, decryptedText: input }]);,
      socket.emit('encrypted_message', msgPayload);,
      setInput('');,
    };,
  `,
    return (,
      <div className="flex flex-col h-[100dvh] bg-[#121212] overflow-hidden">,
        <header className="flex items-center justify-between cs-panel p-4 shrink-0 border-b border-white/5">,
          <div className="flex items-center gap-4">,
            <Link href="/" className="text-cs-orange hover:bg-white/5 p-2 rounded-full">,
              <ChevronLeft size={28} />,
            </Link>,
            <div>,
              <h1 className="text-xl font-bold tracking-widest uppercase flex items-center gap-2">,
                Sekretny Czat <ShieldCheck className="text-green-500" size={20} />,
              </h1>,
              <p className="text-[10px] text-white/50 flex items-center gap-1 mt-1">,
                <LockKeyhole size={10} /> E2EE AKTYWNE,
              </p>,
            </div>,
          </div>,
          <div className="text-xs text-white/30 hidden sm:block text-right">,
            <span className="block">TWÓJ ID:</span>,
            <span className="text-cs-orange font-bold">{userId.toUpperCase()}</span>,
          </div>,
        </header>,
        ,
        <div className="flex-1 overflow-y-auto p-4 flex flex-col gap-4 scrollbar-hide md:max-w-4xl w-full mx-auto self-center">,
          {messages.length === 0 ? (,
            <div className="flex-1 flex flex-col justify-center items-center text-white/30 text-center gap-3">,
              <ShieldCheck size={48} className="text-white/10" />,
              <p className="max-w-xs text-sm tracking-widest leading-relaxed">,
                WIADOMOŒCI S¥ SZYFROWANE PRZED WYS£ANIEM W SIEÆ.,
              </p>,
            </div>,
          ) : (,
            messages.map(msg => {,
              const isMe = msg.sender === userId;,
              return (,
                <div key={msg.id} className={'flex flex-col max-w-[80%] ' + (isMe ? 'self-end items-end' : 'self-start items-start')}>,
                  {!isMe && <span className="text-[10px] text-white/30 mb-1 ml-1">{msg.sender.toUpperCase()}</span>},
                  <div className={'p-3 rounded-lg text-sm tracking-wide ' + (isMe ? 'bg-cs-orange text-black font-semibold' : 'bg-[#333333] text-white border border-white/10')}>,
                    {msg.decryptedText},
                  </div>,
                  <div className="text-[10px] text-white/30 mt-1 flex gap-1 items-center">,
                    <LockKeyhole size={8} /> {msg.time},
                  </div>,
                </div>,
              );,
            }),
          )},
          <div ref={messagesEndRef} />,
        </div>,
  `,
        <form onSubmit={sendMessage} className="p-4 shrink-0 flex gap-2 md:max-w-4xl w-full mx-auto self-center border-t border-white/5">,
          <input ,
            type="text" ,
            value={input},
            onChange={(e) => setInput(e.target.value)},
            placeholder="Bezpieczna wiadomoœæ..." ,
            className="flex-1 bg-[#222222] border border-white/10 rounded-md px-4 py-3 text-sm focus:outline-none focus:border-cs-orange text-white",
          />,
          <button type="submit" className="cs-btn rounded-md flex items-center justify-center min-w-[60px]" disabled={!input.trim()}>,
            <Send size={20} />,
          </button>,
        </form>,
      </div>,
    );,
  }
];

fs.writeFileSync('src/app/chat/page.tsx', lines.join('\n'), 'utf8');
