const fs = require('fs');

const lines = [
  'use client';,
  import React, { useState } from 'react';,
  import Link from 'next/link';,
  import { ChevronLeft, QrCode, ScanLine, ContactlessPayment, ArrowUpRight, ArrowDownLeft, Wallet } from 'lucide-react';,
  import { QRCodeCanvas } from 'qrcode.react';,
  `,
  export default function WalletPage() {,
    const [activeTab, setActiveTab] = useState('NFC');,
    const balance = '14,250.00';,
    const transactions = [,
      { id: 1, title: 'Biedronka', amount: '-45.20', type: 'out', date: 'Dziœ, 14:20' },,
      { id: 2, title: 'Przelew: Jan Kowalski', amount: '+120.00', type: 'in', date: 'Wczoraj, 18:45' },,
      { id: 3, title: 'Gamer Pizza', amount: '-85.50', type: 'out', date: 'Wczoraj, 13:10' },,
      { id: 4, title: 'Wyp³ata z bankomatu', amount: '-200.00', type: 'out', date: '24 Kwi, 10:00' },
    ];,
  `,
    return (,
      <div className="min-h-[100dvh] flex flex-col bg-[#121212] overflow-hidden">,
        <header className="flex items-center justify-between cs-panel p-4 shrink-0 border-b border-white/5">,
          <div className="flex items-center gap-4">,
            <Link href="/" className="text-cs-orange hover:bg-white/5 p-2 rounded-full">,
              <ChevronLeft size={28} />,
            </Link>,
            <div>,
              <h1 className="text-xl font-bold tracking-widest uppercase flex items-center gap-2">,
                PL Portfel <Wallet className="text-cs-orange" size={20} />,
              </h1>,
            </div>,
          </div>,
        </header>,
  `,
        <div className="flex-1 overflow-y-auto p-4 flex flex-col gap-6 md:max-w-2xl w-full mx-auto">,
          ,
          <div className="cs-panel p-6 rounded-2xl relative overflow-hidden border border-white/10 shadow-xl shadow-cs-orange/5 text-center">,
            <div className="absolute top-0 right-0 p-4 opacity-10">,
              <ContactlessPayment size={100} />,
            </div>,
            <h2 className="text-white/50 text-sm tracking-widest font-bold mb-2">DOSTÊPNE ŒRODKI</h2>,
            <div className="text-4xl md:text-5xl font-extrabold text-white tracking-wider mb-6">,
              {balance} <span className="text-cs-orange text-2xl">PLN</span>,
            </div>,
            ,
            <div className="grid grid-cols-2 gap-2 bg-[#121212] p-1 rounded-xl relative z-10">,
              <button ,
                onClick={() => setActiveTab('NFC')},
                className={'py-3 rounded-lg font-bold tracking-widest text-xs flex items-center justify-center gap-2 transition-colors ' + (activeTab === 'NFC' ? 'bg-cs-orange text-black' : 'text-white/50 hover:text-white')},
              >,
                <ContactlessPayment size={16} /> ZBLI¯ENIOWO (NFC),
              </button>,
              <button ,
                onClick={() => setActiveTab('QR_SHOW')},
                className={'py-3 rounded-lg font-bold tracking-widest text-xs flex items-center justify-center gap-2 transition-colors ' + (activeTab.includes('QR') ? 'bg-cs-orange text-black' : 'text-white/50 hover:text-white')},
              >,
                <QrCode size={16} /> KOD QR / BLIK,
              </button>,
            </div>,
          </div>,
  `,
          <div className="cs-panel p-6 rounded-2xl border border-white/5 flex flex-col items-center justify-center min-h-[300px] transition-all relative overflow-hidden">,
            ,
            {activeTab === 'NFC' && (,
              <div className="flex flex-col items-center justify-center gap-6 animate-in fade-in zoom-in duration-300">,
                <div className="w-32 h-32 rounded-full bg-cs-orange/10 flex items-center justify-center relative animate-pulse">,
                  <div className="absolute inset-0 rounded-full border-2 border-cs-orange animate-ping opacity-20"></div>,
                  <ContactlessPayment size={64} className="text-cs-orange" />,
                </div>,
                <div className="text-center">,
                  <h3 className="font-bold text-lg tracking-widest uppercase">Zbli¿ do terminala</h3>,
                  <p className="text-white/40 text-xs mt-2 tracking-wider">Gotowoœæ do bezstykowej p³atnoœci w tle.</p>,
                </div>,
              </div>,
            )},
  `,
            {activeTab.includes('QR') && (,
              <div className="w-full flex flex-col animate-in fade-in slide-in-from-right-4 duration-300">,
                <div className="flex gap-2 mb-6 border-b border-white/10 pb-4">,
                  <button ,
                    onClick={() => setActiveTab('QR_SHOW')},
                    className={'flex-1 pb-2 border-b-2 transition-colors text-sm font-bold tracking-widest ' + (activeTab === 'QR_SHOW' ? 'border-cs-orange text-white' : 'border-transparent text-white/40')},
                  >,
                    MÓJ KOD,
                  </button>,
                  <button ,
                    onClick={() => setActiveTab('QR_SCAN')},
                    className={'flex-1 pb-2 border-b-2 transition-colors text-sm font-bold tracking-widest ' + (activeTab === 'QR_SCAN' ? 'border-cs-orange text-white' : 'border-transparent text-white/40')},
                  >,
                    SKANUJ QR,
                  </button>,
                </div>,
  `,
                {activeTab === 'QR_SHOW' ? (,
                  <div className="flex flex-col items-center gap-4">,
                    <div className="bg-white p-4 rounded-xl shadow-[0_0_20px_rgba(252,160,0,0.15)] mt-2">,
                      <QRCodeCanvas value="PL_SUPERAPP_PAY_TRANSACTION_888" size={200} bgColor={"#ffffff"} fgColor={"#000000"} />,
                    </div>,
                    <p className="text-white/40 text-xs tracking-wider text-center mt-2">Poka¿ ten kod sprzedawcy lub znajomemu, <br/>aby otrzymywaæ p³atnoœæ P2P / Blik.</p>,
                  </div>,
                ) : (,
                  <div className="flex flex-col items-center gap-4 w-full">,
                    <div className="relative w-full max-w-[250px] aspect-square bg-[#0a0a0a] border-2 border-white/20 rounded-xl overflow-hidden flex items-center justify-center shadow-[inset_0_30px_30px_rgba(0,0,0,0.5)]">,
                      <div className="absolute inset-0 transition-opacity bg-[linear-gradient(rgba(255,255,255,0.03)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.03)_1px,transparent_1px)] bg-[size:15px_15px]"></div>,
                      <div className="w-full h-0.5 bg-cs-orange shadow-[0_0_15px_#fca000] absolute top-1/2 opacity-70 animate-[bounce_2s_infinite]"></div>,
                      <ScanLine size={48} className="text-white/20" />,
                    </div>,
                    <p className="text-white/40 text-xs tracking-wider text-center mt-2">Zeskanuj kod terminala albo kod od innego rozmówcy na WeChat.</p>,
                  </div>,
                )},
              </div>,
            )},
          </div>,
  `,
          <div>,
            <h3 className="text-xs text-white/50 tracking-widest font-bold uppercase border-l-2 border-l-cs-orange pl-2 mb-4">Ostatnie Transakcje</h3>,
            <div className="flex flex-col gap-3">,
              {transactions.map(tx => (,
                <div key={tx.id} className="cs-panel p-4 rounded-xl flex items-center justify-between border border-white/5 hover:border-white/10 transition-colors">,
                  <div className="flex items-center gap-3">,
                    <div className={'p-2 rounded-lg ' + (tx.type === 'in' ? 'bg-green-500/10 text-green-500' : 'bg-white/5 text-white')}>,
                      {tx.type === 'in' ? <ArrowDownLeft size={20} /> : <ArrowUpRight size={20} />},
                    </div>,
                    <div>,
                      <h4 className="font-bold tracking-wider text-sm">{tx.title}</h4>,
                      <span className="text-[10px] text-white/40">{tx.date}</span>,
                    </div>,
                  </div>,
                  <div className={'font-bold tracking-widest ' + (tx.type === 'in' ? 'text-green-500' : 'text-white')}>,
                    {tx.amount} PLN,
                  </div>,
                </div>,
              ))},
            </div>,
          </div>,
        </div>,
      </div>,
    );,
  }
];

fs.writeFileSync('src/app/wallet/page.tsx', lines.join('\n'), 'utf8');
